### ISSUE TITLE
Add clsx package

### ISSUE THREAD

**Issue by bjornallvin** [DPC-Nordics/dpc-next#11]

**Comment by bjornallvin** [comment]
An maybe refactor the Button component as an example of its usage

**Comment by GuptaSiddhant** [comment]
There is no performance boost with clsx but it definitely improves DX when dealing with different possible values of className.

Using clsx allows you to

pass empty className string
pass undefined className
conditionally pass a particular className as it handles truthy and falsy values, eg.
className={clsx("p-4", ... , isFeatured && "scale-105" )}
Essentially, it can accept className values in any format or type (string, object, array) and create className string.
I personally use clsx at least to handle the merging of props.className with pre-defined className string.

More examples at https://github.com/lukeed/clsx#usage

**Comment by bjornallvin** [comment]
We hould discuss this I think.  IMHO I don't actully think that this is an improvment on readability or DX. 🤔.  When looking at the Button component code.

**Comment by GuptaSiddhant** [comment]
A discussion would be good.

My argument is that defining Tailwind classes outside `className` attribute, Tailwind's vs-code extension does not provide any intellisense or auto-complete.

**Comment by bjornallvin** [comment]
Intellisense is important. Maybe not as important as writing clean code :-). However there is a fix for the intellisense. There is a property in settings where you can add custom regexps for where the intellisense should pop up.  For example this setting will show intellisense in all uses of the clsx function:

```
"tailwindCSS.experimental.classRegex": [
    ["clsx\\(([^)]*)\\)", "(?:'|\"|`)([^']*)(?:'|\"|`)"]
  ]
```

**Comment by bjornallvin** [comment]
![image](https://user-images.githubusercontent.com/2735574/145552484-fe60780b-5d1a-49a3-b680-e06c95bdc9db.png)

**Comment by GuptaSiddhant** [comment]
@bjornallvin, that is actually much better. The regex you shared currently work with classes wrapped with `clsx` function. So should we move forward with adding and using `clsx`?
