### ISSUE TITLE
Story for ProductDetails is broken

### ISSUE THREAD

**Issue by bjornallvin** [DPC-Nordics/dpc-next#15]
Configuration issue when using Next image component.

![image](https://user-images.githubusercontent.com/2735574/145557018-7c278388-2d05-4a69-a361-70e7f8619b9e.png)

**Comment by GuptaSiddhant** [comment]
https://github.com/vercel/next.js/issues/18393

**Comment by bjornallvin** [comment]
Solution was found in this blog post: https://storybook.js.org/blog/get-started-with-storybook-and-next-js/

Under heading "De-optimize Next.js Image in stories"

**Comment by bjornallvin** [comment]
Solution was found in this blog post: https://storybook.js.org/blog/get-started-with-storybook-and-next-js/

Under heading "De-optimize Next.js Image in stories"
